### ISSUE TITLE
Add Decklink sources to list

### ISSUE THREAD

**Issue by MoonfirePDX** [MechanicallyDev/OBS-Anti-Mic-Monitoring-Desync#3]
I added the source type "decklink-input" to the list to work around the same problem this addresses, but for my Blackmagic capture card and tested that it correctly works around the OBS bug.
Thank you for making this tool!

**Comment by MechanicallyDev** [comment]
Thanks you very much for sharing the source type! I'm glad this script helped you.

Just so I can add it correctly, did you add the source type as "decklink-input" or as "decklink_input_capture" (this format is more common in OBS documentation)?

**Comment by MechanicallyDev** [comment]
UPDATE: As per the latest update, refering to an audio API is no longer needed and the script should work for every input 
 source (including video sources).

Issue closed. Thanks for the feedback @MoonfirePDX.
