### ISSUE TITLE
Not Showing Sources

### ISSUE THREAD

**Issue by darkartist69** [MechanicallyDev/OBS-Anti-Mic-Monitoring-Desync#6]
I loaded the script and installed python. Have restarted OBS, removed and added the script back. verified that python was installed but in the tools > script area it does not show any options. it says "no properties available" 
here is the link to the log file:
https://obsproject.com/logs/cqnm7LM8kgsZuZ-O

thank you for looking into this!
~DA

**Comment by MarcusBuer** [comment]
Hi @darkartist69, thanks for reporting this issue.

According to the log, OBS could not find the correct version of Python on your machine. 

```
13:10:44.838: LoadLibrary failed for 'C:/Users/User/AppData/Local/Programs/Python/Python311/python36.dll': The specified module could not be found.

13:10:44.838: [Python] Could not load library: C:/Users/User/AppData/Local/Programs/Python/Python311/python36.dll
```


Please make sure Python 3.6 is installed, as newer versions won't work on OBS 37.
Link to the latest pre-compiled installer of Python 3.6: https://www.python.org/ftp/python/3.6.8/python-3.6.8-amd64.exe


After installing Python 3.6, open OBS, and on the Scripts window there is a second tab called "Python Settings" where you can change the path to where you installed Python. The standard path is "C:/Program Files/Python36" if it was installed for all users, or if it was installed only for the current user it is in: "C:/Users/User/AppData/Local/Programs/Python/Python36".

After configuring OBS with the correct Python path you can load scripts on the "Scripts" tab.

**Comment by darkartist69** [comment]
Such a simple fix ;) thank you.  It's showing.  I'm going to test it this
Friday.

Thank you so much
~DA

**Comment by MarcusBuer** [comment]
No problem @darkartist69.

I'm closing the issue as it seems it was fixed by installing the correct version of python.
If you run into any more issues please open another issue to let me know.

I hope this script helps you.
